/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityId = bigint;
export type ActivityType = { 'contact' : null } |
  { 'note' : null } |
  { 'event' : null };
export interface CampaignActivity {
  'id' : ActivityId,
  'activityType' : ActivityType,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : string,
  'electorateId' : ElectorateId,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Electorate {
  'id' : ElectorateId,
  'region' : string,
  'province' : string,
  'name' : string,
  'updatedAt' : Timestamp,
  'registeredVoters' : bigint,
  'supportLevel' : SupportLevel,
  'notes' : string,
  'campaignManager' : string,
  'seatType' : SeatType,
}
export type ElectorateId = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface NationalSummary {
  'totalRegisteredVoters' : bigint,
  'totalActivities' : bigint,
  'countsBySupportLevel' : Array<SupportLevelCount>,
  'countsByProvince' : Array<ProvinceCount>,
  'totalProvinces' : bigint,
  'totalElectorates' : bigint,
}
export interface NewActivity {
  'activityType' : ActivityType,
  'date' : Timestamp,
  'description' : string,
}
export interface ProvinceCount { 'province' : string, 'count' : bigint }
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type SeatType = { 'open' : null } |
  { 'regional' : null };
export type SupportLevel = { 'Weak' : null } |
  { 'Strong' : null } |
  { 'Opposed' : null } |
  { 'Undecided' : null } |
  { 'Leaning' : null };
export interface SupportLevelCount {
  'count' : bigint,
  'supportLevel' : SupportLevel,
}
export type Timestamp = bigint;
export interface UpdateCampaignDetails {
  'supportLevel' : SupportLevel,
  'notes' : string,
  'campaignManager' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addActivity' : ActorMethod<
    [ElectorateId, NewActivity],
    [] | [CampaignActivity]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getElectorate' : ActorMethod<[ElectorateId], [] | [Electorate]>,
  'getNationalSummary' : ActorMethod<[], NationalSummary>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActivities' : ActorMethod<[ElectorateId], Array<CampaignActivity>>,
  'listElectorates' : ActorMethod<[], Array<Electorate>>,
  'listRecentActivities' : ActorMethod<[bigint], Array<CampaignActivity>>,
  'schema' : ActorMethod<[], string>,
  'updateCampaignDetails' : ActorMethod<
    [ElectorateId, UpdateCampaignDetails],
    [] | [Electorate]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];