/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ElectorateId = IDL.Nat;
export const ActivityType = IDL.Variant({
  'contact' : IDL.Null,
  'note' : IDL.Null,
  'event' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const NewActivity = IDL.Record({
  'activityType' : ActivityType,
  'date' : Timestamp,
  'description' : IDL.Text,
});
export const ActivityId = IDL.Nat;
export const CampaignActivity = IDL.Record({
  'id' : ActivityId,
  'activityType' : ActivityType,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'electorateId' : ElectorateId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const SupportLevel = IDL.Variant({
  'Weak' : IDL.Null,
  'Strong' : IDL.Null,
  'Opposed' : IDL.Null,
  'Undecided' : IDL.Null,
  'Leaning' : IDL.Null,
});
export const SeatType = IDL.Variant({
  'open' : IDL.Null,
  'regional' : IDL.Null,
});
export const Electorate = IDL.Record({
  'id' : ElectorateId,
  'region' : IDL.Text,
  'province' : IDL.Text,
  'name' : IDL.Text,
  'updatedAt' : Timestamp,
  'registeredVoters' : IDL.Nat,
  'supportLevel' : SupportLevel,
  'notes' : IDL.Text,
  'campaignManager' : IDL.Text,
  'seatType' : SeatType,
});
export const SupportLevelCount = IDL.Record({
  'count' : IDL.Nat,
  'supportLevel' : SupportLevel,
});
export const ProvinceCount = IDL.Record({
  'province' : IDL.Text,
  'count' : IDL.Nat,
});
export const NationalSummary = IDL.Record({
  'totalRegisteredVoters' : IDL.Nat,
  'totalActivities' : IDL.Nat,
  'countsBySupportLevel' : IDL.Vec(SupportLevelCount),
  'countsByProvince' : IDL.Vec(ProvinceCount),
  'totalProvinces' : IDL.Nat,
  'totalElectorates' : IDL.Nat,
});
export const UpdateCampaignDetails = IDL.Record({
  'supportLevel' : SupportLevel,
  'notes' : IDL.Text,
  'campaignManager' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addActivity' : IDL.Func(
      [ElectorateId, NewActivity],
      [IDL.Opt(CampaignActivity)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getElectorate' : IDL.Func([ElectorateId], [IDL.Opt(Electorate)], ['query']),
  'getNationalSummary' : IDL.Func([], [NationalSummary], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActivities' : IDL.Func(
      [ElectorateId],
      [IDL.Vec(CampaignActivity)],
      ['query'],
    ),
  'listElectorates' : IDL.Func([], [IDL.Vec(Electorate)], ['query']),
  'listRecentActivities' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CampaignActivity)],
      ['query'],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateCampaignDetails' : IDL.Func(
      [ElectorateId, UpdateCampaignDetails],
      [IDL.Opt(Electorate)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ElectorateId = IDL.Nat;
  const ActivityType = IDL.Variant({
    'contact' : IDL.Null,
    'note' : IDL.Null,
    'event' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const NewActivity = IDL.Record({
    'activityType' : ActivityType,
    'date' : Timestamp,
    'description' : IDL.Text,
  });
  const ActivityId = IDL.Nat;
  const CampaignActivity = IDL.Record({
    'id' : ActivityId,
    'activityType' : ActivityType,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'electorateId' : ElectorateId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const SupportLevel = IDL.Variant({
    'Weak' : IDL.Null,
    'Strong' : IDL.Null,
    'Opposed' : IDL.Null,
    'Undecided' : IDL.Null,
    'Leaning' : IDL.Null,
  });
  const SeatType = IDL.Variant({ 'open' : IDL.Null, 'regional' : IDL.Null });
  const Electorate = IDL.Record({
    'id' : ElectorateId,
    'region' : IDL.Text,
    'province' : IDL.Text,
    'name' : IDL.Text,
    'updatedAt' : Timestamp,
    'registeredVoters' : IDL.Nat,
    'supportLevel' : SupportLevel,
    'notes' : IDL.Text,
    'campaignManager' : IDL.Text,
    'seatType' : SeatType,
  });
  const SupportLevelCount = IDL.Record({
    'count' : IDL.Nat,
    'supportLevel' : SupportLevel,
  });
  const ProvinceCount = IDL.Record({
    'province' : IDL.Text,
    'count' : IDL.Nat,
  });
  const NationalSummary = IDL.Record({
    'totalRegisteredVoters' : IDL.Nat,
    'totalActivities' : IDL.Nat,
    'countsBySupportLevel' : IDL.Vec(SupportLevelCount),
    'countsByProvince' : IDL.Vec(ProvinceCount),
    'totalProvinces' : IDL.Nat,
    'totalElectorates' : IDL.Nat,
  });
  const UpdateCampaignDetails = IDL.Record({
    'supportLevel' : SupportLevel,
    'notes' : IDL.Text,
    'campaignManager' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addActivity' : IDL.Func(
        [ElectorateId, NewActivity],
        [IDL.Opt(CampaignActivity)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getElectorate' : IDL.Func(
        [ElectorateId],
        [IDL.Opt(Electorate)],
        ['query'],
      ),
    'getNationalSummary' : IDL.Func([], [NationalSummary], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActivities' : IDL.Func(
        [ElectorateId],
        [IDL.Vec(CampaignActivity)],
        ['query'],
      ),
    'listElectorates' : IDL.Func([], [IDL.Vec(Electorate)], ['query']),
    'listRecentActivities' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CampaignActivity)],
        ['query'],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateCampaignDetails' : IDL.Func(
        [ElectorateId, UpdateCampaignDetails],
        [IDL.Opt(Electorate)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };