/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type ActivityId = bigint;
export interface CampaignActivity {
    id: ActivityId;
    activityType: ActivityType;
    date: Timestamp;
    createdAt: Timestamp;
    description: string;
    electorateId: ElectorateId;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface Electorate {
    id: ElectorateId;
    region: string;
    province: string;
    name: string;
    updatedAt: Timestamp;
    registeredVoters: bigint;
    supportLevel: SupportLevel;
    notes: string;
    campaignManager: string;
    seatType: SeatType;
}
export type ElectorateId = bigint;
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface NationalSummary {
    totalRegisteredVoters: bigint;
    totalActivities: bigint;
    countsBySupportLevel: Array<SupportLevelCount>;
    countsByProvince: Array<ProvinceCount>;
    totalProvinces: bigint;
    totalElectorates: bigint;
}
export interface NewActivity {
    activityType: ActivityType;
    date: Timestamp;
    description: string;
}
export interface ProvinceCount {
    province: string;
    count: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface SupportLevelCount {
    count: bigint;
    supportLevel: SupportLevel;
}
export type Timestamp = bigint;
export interface UpdateCampaignDetails {
    supportLevel: SupportLevel;
    notes: string;
    campaignManager: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum ActivityType {
    contact = "contact",
    note = "note",
    event = "event"
}
export enum SeatType {
    open = "open",
    regional = "regional"
}
export enum SupportLevel {
    Weak = "Weak",
    Strong = "Strong",
    Opposed = "Opposed",
    Undecided = "Undecided",
    Leaning = "Leaning"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addActivity(electorateId: ElectorateId, input: NewActivity): Promise<CampaignActivity | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    execute(qJson: string): Promise<Result>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getElectorate(id: ElectorateId): Promise<Electorate | null>;
    getNationalSummary(): Promise<NationalSummary>;
    isCallerAdmin(): Promise<boolean>;
    listActivities(electorateId: ElectorateId): Promise<Array<CampaignActivity>>;
    listElectorates(): Promise<Array<Electorate>>;
    listRecentActivities(limit: bigint): Promise<Array<CampaignActivity>>;
    schema(): Promise<string>;
    updateCampaignDetails(id: ElectorateId, details: UpdateCampaignDetails): Promise<Electorate | null>;
}
import type { ActivityId as _ActivityId, ActivityType as _ActivityType, CampaignActivity as _CampaignActivity, Cell as _Cell, Electorate as _Electorate, ElectorateId as _ElectorateId, Error as _Error, NationalSummary as _NationalSummary, NewActivity as _NewActivity, ProvinceCount as _ProvinceCount, Result as _Result, Result__1 as _Result__1, SeatType as _SeatType, SupportLevel as _SupportLevel, SupportLevelCount as _SupportLevelCount, Timestamp as _Timestamp, UpdateCampaignDetails as _UpdateCampaignDetails, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addActivity(arg0: ElectorateId, arg1: NewActivity): Promise<CampaignActivity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0, to_candid_NewActivity_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0, to_candid_NewActivity_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getElectorate(arg0: ElectorateId): Promise<Electorate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getElectorate(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElectorate(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNationalSummary(): Promise<NationalSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getNationalSummary();
                return from_candid_NationalSummary_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNationalSummary();
            return from_candid_NationalSummary_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActivities(arg0: ElectorateId): Promise<Array<CampaignActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivities(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivities(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listElectorates(): Promise<Array<Electorate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listElectorates();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listElectorates();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRecentActivities(arg0: bigint): Promise<Array<CampaignActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecentActivities(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecentActivities(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateCampaignDetails(arg0: ElectorateId, arg1: UpdateCampaignDetails): Promise<Electorate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCampaignDetails(arg0, to_candid_UpdateCampaignDetails_n34(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCampaignDetails(arg0, to_candid_UpdateCampaignDetails_n34(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return "contact" in value ? ActivityType.contact : "note" in value ? ActivityType.note : "event" in value ? ActivityType.event : value;
}
function from_candid_CampaignActivity_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignActivity): CampaignActivity {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Electorate_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Electorate): Electorate {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_NationalSummary_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NationalSummary): NationalSummary {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SeatType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeatType): SeatType {
    return "open" in value ? SeatType.open : "regional" in value ? SeatType.regional : value;
}
function from_candid_SupportLevelCount_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportLevelCount): SupportLevelCount {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_SupportLevel_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportLevel): SupportLevel {
    return "Weak" in value ? SupportLevel.Weak : "Strong" in value ? SupportLevel.Strong : "Opposed" in value ? SupportLevel.Opposed : "Undecided" in value ? SupportLevel.Undecided : "Leaning" in value ? SupportLevel.Leaning : value;
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Electorate]): Electorate | null {
    return value.length === 0 ? null : from_candid_Electorate_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CampaignActivity]): CampaignActivity | null {
    return value.length === 0 ? null : from_candid_CampaignActivity_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ActivityId;
    activityType: _ActivityType;
    date: _Timestamp;
    createdAt: _Timestamp;
    description: string;
    electorateId: _ElectorateId;
}): {
    id: ActivityId;
    activityType: ActivityType;
    date: Timestamp;
    createdAt: Timestamp;
    description: string;
    electorateId: ElectorateId;
} {
    return {
        id: value.id,
        activityType: from_candid_ActivityType_n11(_uploadFile, _downloadFile, value.activityType),
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        electorateId: value.electorateId
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n15(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n19(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ElectorateId;
    region: string;
    province: string;
    name: string;
    updatedAt: _Timestamp;
    registeredVoters: bigint;
    supportLevel: _SupportLevel;
    notes: string;
    campaignManager: string;
    seatType: _SeatType;
}): {
    id: ElectorateId;
    region: string;
    province: string;
    name: string;
    updatedAt: Timestamp;
    registeredVoters: bigint;
    supportLevel: SupportLevel;
    notes: string;
    campaignManager: string;
    seatType: SeatType;
} {
    return {
        id: value.id,
        region: value.region,
        province: value.province,
        name: value.name,
        updatedAt: value.updatedAt,
        registeredVoters: value.registeredVoters,
        supportLevel: from_candid_SupportLevel_n25(_uploadFile, _downloadFile, value.supportLevel),
        notes: value.notes,
        campaignManager: value.campaignManager,
        seatType: from_candid_SeatType_n26(_uploadFile, _downloadFile, value.seatType)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalRegisteredVoters: bigint;
    totalActivities: bigint;
    countsBySupportLevel: Array<_SupportLevelCount>;
    countsByProvince: Array<_ProvinceCount>;
    totalProvinces: bigint;
    totalElectorates: bigint;
}): {
    totalRegisteredVoters: bigint;
    totalActivities: bigint;
    countsBySupportLevel: Array<SupportLevelCount>;
    countsByProvince: Array<ProvinceCount>;
    totalProvinces: bigint;
    totalElectorates: bigint;
} {
    return {
        totalRegisteredVoters: value.totalRegisteredVoters,
        totalActivities: value.totalActivities,
        countsBySupportLevel: from_candid_vec_n29(_uploadFile, _downloadFile, value.countsBySupportLevel),
        countsByProvince: value.countsByProvince,
        totalProvinces: value.totalProvinces,
        totalElectorates: value.totalElectorates
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    count: bigint;
    supportLevel: _SupportLevel;
}): {
    count: bigint;
    supportLevel: SupportLevel;
} {
    return {
        count: value.count,
        supportLevel: from_candid_SupportLevel_n25(_uploadFile, _downloadFile, value.supportLevel)
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupportLevelCount>): Array<SupportLevelCount> {
    return value.map((x)=>from_candid_SupportLevelCount_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CampaignActivity>): Array<CampaignActivity> {
    return value.map((x)=>from_candid_CampaignActivity_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Electorate>): Array<Electorate> {
    return value.map((x)=>from_candid_Electorate_n23(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return value == ActivityType.contact ? {
        contact: null
    } : value == ActivityType.note ? {
        note: null
    } : value == ActivityType.event ? {
        event: null
    } : value;
}
function to_candid_NewActivity_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewActivity): _NewActivity {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SupportLevel_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupportLevel): _SupportLevel {
    return value == SupportLevel.Weak ? {
        Weak: null
    } : value == SupportLevel.Strong ? {
        Strong: null
    } : value == SupportLevel.Opposed ? {
        Opposed: null
    } : value == SupportLevel.Undecided ? {
        Undecided: null
    } : value == SupportLevel.Leaning ? {
        Leaning: null
    } : value;
}
function to_candid_UpdateCampaignDetails_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateCampaignDetails): _UpdateCampaignDetails {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supportLevel: SupportLevel;
    notes: string;
    campaignManager: string;
}): {
    supportLevel: _SupportLevel;
    notes: string;
    campaignManager: string;
} {
    return {
        supportLevel: to_candid_SupportLevel_n36(_uploadFile, _downloadFile, value.supportLevel),
        notes: value.notes,
        campaignManager: value.campaignManager
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityType: ActivityType;
    date: Timestamp;
    description: string;
}): {
    activityType: _ActivityType;
    date: _Timestamp;
    description: string;
} {
    return {
        activityType: to_candid_ActivityType_n7(_uploadFile, _downloadFile, value.activityType),
        date: value.date,
        description: value.description
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
